name: pre-commit
description: run pre-commit in backend folder
inputs:
    extra_args:
        description: options to pass to pre-commit run
        required: false
        # default: "--all-files"
runs:
    using: composite
    steps:
        - run: python -m pip install pre-commit
          shell: bash
        - run: python -m pip freeze --local
          shell: bash
        - uses: actions/cache@v4
          with:
              path: ~/.cache/pre-commit
              key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('backend/.pre-commit-config.yaml') }}
        - run: cd backend/ && pre-commit run --files backend/* --show-diff-on-failure --color=always ${{ inputs.extra_args }}
          shell: bash
